### ISSUE TITLE
Bug in z-textblock.c

### ISSUE THREAD

**Issue by Cuboideb** [NickMcConnell/FirstAgeAngband#129]
After updating my working copy. I was using a wand of lightning bolts on a red bat. Got this [Bug](https://ibb.co/6ZT9RKg)

**Comment by NickMcConnell** [comment]
This is probably on error in monster lore - did you have a monster recall window open?

**Comment by Cuboideb** [comment]
Just one window, but this character is a couple of weeks old. Perhaps the lore file is invalid

**Comment by NickMcConnell** [comment]
Ah yes, the recent release broke savefiles, and changed some monster names.  I think we can assume that's it.
