### ISSUE TITLE
Crashing on switching levels

### ISSUE THREAD

**Issue by DeathByEnnui** [NickMcConnell/FirstAgeAngband#131]
First time player. Downloaded the windows binary yesterday. Nice so far, but it becomes unplayable as crashes prevent me from entering some levels. 

This char is in Talath Dirnen 26, trying to head left to get to the next dungeon. Every time I try to enter that map though, the game crashes. 

Assertion Failed
Cave-square.c
Line: 1400

I tried the OS X binary and I ran into the exact same issue. I can provide save file if it helps.

**Comment by NickMcConnell** [comment]
Savefile would help, thanks - you can drop it here, or email it to me at nckmccnnll at gmail

**Comment by DeathByEnnui** [comment]
[Endreth.zip](https://github.com/NickMcConnell/FirstAgeAngband/files/5649526/Endreth.zip)

Further playing also shows it happen when I try to enter the overworld map over another dungeon too. It's possible it's happening on every overworld map with a dungeon.

![image](https://user-images.githubusercontent.com/36737557/101292316-d0c77f00-37dc-11eb-940e-24da1e257289.png)

**Comment by NickMcConnell** [comment]
Sorry, hope to get to this soon - this is 2.0beta1?

**Comment by NickMcConnell** [comment]
Thanks, I will get to this eventually

**Comment by NickMcConnell** [comment]
OK, It looks like this is from 2.0beta - at least it loads in that, and not in 2.0beta1.  There were a lot of changes between those two, so I don't think it's worth chasing this down as events have passed it by.
