### ISSUE TITLE
Economy Borked

### ISSUE THREAD

**Issue by damedley** [NickMcConnell/FirstAgeAngband#14]
For some reason, now I'm starting with 0 AU and the prices are crazy. Eg:
Arndal Beast-Slayer (Half-Elf)                                                  Weapon Smiths (10000)                                  
                                                                                                                                        
 Store Inventory                                                                  Weight      Price                                     
 a) a Cutlass (1d8) (+0,+0)                                                      11.0 lb          1                                     
 c) a Katana (3d5) (+0,+0)                                                       12.0 lb          1                                     
 f) an Awl-Pike (1d8) (+0,+0)                                                    16.0 lb          1                                     
 h) a Pike (2d5) (+0,+0)                                                         16.0 lb          1                                     
 j) a Lucerne Hammer (2d5) (+0,+0)                                               12.0 lb          1                                     
 m) a Whip (1d3) (+2,+1)                                                          3.0 lb          1                                     
 n) a Whip (1d3) (+0,+0)                                                          3.0 lb          1                                     
 o) a Short Bow (x2) (+0,+0)                                                      3.0 lb          1                                     
 q) a Bolt (1d5) (+3,+5)                                                          0.3 lb   20631913                             

This may be related to my earlier savefile corruption issue, since I can't completely delete those files on Angband.live. I'm not too worried if it just affects me, but thought I'd report it in case it's more widespread.

**Comment by NickMcConnell** [comment]
That's entertaining, and probably worth keeping an eye on.
The game is 'playable', but I'm replacing big chunks of it without really considering the wider effects; if that's the weirdest thing that happens, I'll be surprised...

**Comment by NickMcConnell** [comment]
Looks fine now

**Comment by NickMcConnell** [comment]
OK, apparently still not great as of 55a5cf5cf :
"Sell 2 Daggers (1d4) (+0,+0) for 884 gold?" - Mitze
"40 Iron Shots (1d4) (+0,+0) Price 962" - Mitze
"sold 2 daggers for 774 at travelling merchant" - Klassik

**Comment by NickMcConnell** [comment]
Fixed a couple of bugs in 2db04bba7, leaving this open as prices still need work

**Comment by NickMcConnell** [comment]
"May in fact not actually be a bug, but curses don't appear to have an effect on pricing; I checked what I would get for a cursed amulet I was carrying, completely uncursed it, and it fetched the same price afterwards." - MITZE

**Comment by NickMcConnell** [comment]
"Enchanted ammo is still far more valuable than anything else; a stack easily goes for 6-10k, while most armor egos are a few thousand and the weapons generally aren't much better." - MITZE

**Comment by NickMcConnell** [comment]
Big nerf to brands and slays in 67b96c6e5, we'll see where we are after that.

**Comment by NickMcConnell** [comment]
Calling this done for now
