### ISSUE TITLE
Region map doesn't work

### ISSUE THREAD

**Issue by Valoren** [NickMcConnell/FirstAgeAngband#15]
In FAangband 1.4.4, pressing "M" bings the current zone map and then the whole region map.  FirstAgeangband shows current zone map but the region
map doesn't show.

**Comment by NickMcConnell** [comment]
Yep, still to be implemented.

**Comment by NickMcConnell** [comment]
This is now basically working - good enough for beta, kicking to 2.0

**Comment by NickMcConnell** [comment]
Scrolling still needs improvement, and it would be good to have this as a separate command

**Comment by NickMcConnell** [comment]
Separate command not really a win, so calling this as of a5fbe41a4.
