### ISSUE TITLE
Crash: Going from underground to wilderness

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#168]
Zabutor has run into another crash; as far as I've gathered they fell through a trap door into the underground two-three wilderness maps west of Khazad Dum, and when they try to go back up to the wilderness it crashes with the error message:

/home/angband/games/firstageangband/nightly/firstageangband: Failed to find cave profile!

As far as I know Zabutor has saved next to the stairs; if you want the save file you'll have to contact Gwarl personally, he isn't appearing on the server lately.

**Comment by NickMcConnell** [comment]
Right, have done so.

**Comment by ThatGitMITZE** [comment]
Actually, it's a moot point now; Zabutor got out via ?Recall, which didn't cause a crash. Save doesn't exist anymore.

**Comment by NickMcConnell** [comment]
Can confirm this happens on Eriador 9 after saving and reloading while in underworld.
