### ISSUE TITLE
World map SDL2 issue

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/FirstAgeAngband#169]
Doesn't transition properly from level map to world map - Sasquatch

**Comment by NickMcConnell** [comment]
Maybe give world map its own command?

**Comment by fumsoft** [comment]
Term->view_map_hook() is called from ui-map.c, line 755. SDL2 frontend sets its custom hook in main-sdl2.c, line 5216:
"subwindow->term->view_map_hook = term_view_map_hook". To disable it and return to the standard Angband behaviour, replace the line with:
"subwindow->term->view_map_hook = NULL"

**Comment by fumsoft** [comment]
I've taken a look, in your ui-map.c it's line 1069. Probably just don't call the hook, since none of the current frontends knows what to do with it.

**Comment by NickMcConnell** [comment]
Thanks 😄
