### ISSUE TITLE
TREASURE or OBJECT drops

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#171]
Living Dungeons claim to drop up to 14 treasures or objects; I've killed a number due to having *Ac, and I've never seen them drop an object, only treasure. Paying attention afterwards, I've also noticed there were some other monsters (mostly low-level [p]) that supposedly drop either objects or treasure that never seemed to drop the former, only the latter.

**Comment by NickMcConnell** [comment]
It should be just "treasures", and that's what it says for me, but I think that's because I have copied monster.txt over.  This is a genuine bug, also in V - the game takes note of how many objects and treasures get dropped every time, but doesn't do anything with the information 🙄
