### ISSUE TITLE
RFE: Buff Gwindor's lite intensity/radius

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#186]
Finally found Gwindor at Nargo DL42 . . . except I have a lantern of brightness, which actually seems to be a better light than Gwindor despite the hype in the latter's flavor text?

Lantern of Brightness seems to be radius 3, intensity 4.
Gwindor seems to be radius 2, intensity 3.

Hardly lives up to the flavor text, no?

**Comment by NickMcConnell** [comment]
Hm, I wonder if that's a problem for the lights in V as well.

**Comment by ThatGitMITZE** [comment]
Addendum to this: [I]nspecting Gwindor reveals that it has +3 lite, intensity 3. The lantern of brightness, on the other hand, has +1 lite, intensity 4.

Now, the latter makes sense insofar as it matches my knowledge to how the lighting system is supposed to work; all lights that provide lite have an innate 1 intensity and at least lite your own square, and also any radius you have also adds to your lite intensity. However, while that makes sense using the context of the lantern of brightness (lanterns as a base type have 2 radius, so a mundane lantern has 2 radius/3 intensity and a brightness one has 3 radius/4 intensity), it doesn't make sense when you look at Gwindor (or rather, Gwindor doesn't make sense when you look at *it* using the previous mechanics assumptions); Gwindor says it gives +3 light with intensity 3, but it actually only seems to give 2 radius, making it look like it has no innate lite radius or intensity of its own.

**Comment by NickMcConnell** [comment]
Yep, problem here is I totally missed artifact lights when I upgraded the V lighting system.  They should all be LIGHT[4].
