### ISSUE TITLE
Bug: Mage's 'Electric Arc'

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#193]
The Mage's 'Electric Arc' spell has a beam length that improves with CL; however, its claimed length eventually becomes drastically greater than player LOS and doesn't actually seem to affect things outside of LOS besides.

Can't tell whether if it's supposed to have super-long range that just doesn't work right, or if it's just a info display error.

**Comment by NickMcConnell** [comment]
Nothing goes more than player LoS (in practice), so it's an info problem.

**Comment by NickMcConnell** [comment]
Fixed in 66b030c2c
