### ISSUE TITLE
Lock Up: Wilderness Map-to-Map Travel

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#194]
Rolanako had the game lock up on him going from Desert 54 to Desert 56 in Standard wilderness; submitting as a different issue because with the other one the game crashed, not locked up.

EDIT: Also, when the game forced closed and then reloaded it put him in the zone he was trying to enter.

**Comment by NickMcConnell** [comment]
I'm putting this as Ongoing with all the other sporadic bugs.  More testing required, really.

**Comment by NickMcConnell** [comment]
No longer a problem according to MITZE
