### ISSUE TITLE
Bug?: Solid Colour Blocks at High Skill Levels

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#196]
See http://angband.oook.cz/forum/showpost.php?p=153894&postcount=346

**Comment by NickMcConnell** [comment]
Not intentional.

**Comment by ThatGitMITZE** [comment]
Not quite fixed yet; put on more device stuff and at 175 it turns into a solid green block again; even more device stuff and it goes back to a white visible number at 194.

**Comment by ThatGitMITZE** [comment]
Equipping Maeglin gauntlets takes my devices from 167 to ~197 now, except I can only guess at the latter number because it straight-up breaks the display; unlike before (where I could still get the number by highlighting the block of color), now there is no number because it's just a black space and highlighting reveals nothing.

**Comment by ThatGitMITZE** [comment]
Found a pair of +4 Magic Mastery gauntlets, taking my skill to 207. I still can't see it in-game, but apparently a dump displays it correctly.

**Comment by NickMcConnell** [comment]
Fixes are still just band-aids, I need a proper one.

**Comment by ThatGitMITZE** [comment]
Indeed you do; it's still possible gain enough Magic Device skill with an ideal kit and character to break the display (happens somewhere from 219 to 224, inclusive).

**Comment by NickMcConnell** [comment]
Yep, it's at 13*17, so 221
