### ISSUE TITLE
Bug: Mushroom of Emergency

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#203]
"When eaten, it selects one of , extends 40% fire resistance for 0 turns, extends 40% cold resistance for 0 turns, selects one of , heals 200 hitpoints and feeds you for 500 turns (5 percent)."

The effect when eaten seems to use the same dice for all of rFire rCold and Hallucination; IIRC only rFire and rCold had the same potential duration length, with Hallucination having a considerably longer potential length.

**Comment by NickMcConnell** [comment]
The durations were actually all the same (changed to that in V in 2017).  The message is a bug, though.

**Comment by NickMcConnell** [comment]
Fixed in 86587218c
