### ISSUE TITLE
Bug: unIDed Armour Combat Bonuses

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#204]
Still occasionally finding unIDed armour where it explicitly says it has (+0,+0) before you ID the runes on it.

"You have no room for Chain Mail (+0,+0) [32,+31] {??}."

**Comment by ThatGitMITZE** [comment]
Armour ended up being 'of Anchoring'; the non-existant combat bonuses disappeared after it IDed.

**Comment by NickMcConnell** [comment]
Not 100% sure this is fixed, but let's hope.
