### ISSUE TITLE
Bug: Initial Spawning in Wilderness Levels w/ Connected Stairs

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#214]
In the process of other bugtesting, I've had to generate wilderness levels in quick succession.

I've noticed while doing so that sometimes, rarely, (with connected stairs on) that one does not always spawn on the staircase when spawning in a new level (but so far I have always spawned at least directly next to the stairs if not on them).

Connected Stairs, with Extended Wilderness (if it makes a difference).

**Comment by NickMcConnell** [comment]
I think I've noticed this too.

**Comment by ThatGitMITZE** [comment]
Just had an instance where I did not spawn at least right next to a staircase.

**Comment by NickMcConnell** [comment]
Possibly improved by dd2472ce7 - we'll se if it keeps happening.

**Comment by NickMcConnell** [comment]
This is probably fixed now.

**Comment by NickMcConnell** [comment]
Calling it.
