### ISSUE TITLE
Crash: On Player Ghost Sighting

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#215]
Rarely, coming within LOS of a player ghost causes a crash; I've had it happen to me and I believe I've heard other players on the webserver complain about it too.

**Comment by NickMcConnell** [comment]
My guess is them trying to speak and failing, probably due to a bad bones file.

**Comment by NickMcConnell** [comment]
Not seeing this happening now, will close in a few days if still nothing.

**Comment by NickMcConnell** [comment]
8 is a few.
