### ISSUE TITLE
Bug: Preloaded Player Ghosts

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#216]
I feel pretty confident now that something's wrong with the preloaded player ghosts; I haven't seen any online or offline, and as far as I've heard I haven't heard anyone else talk about finding them online either.

Conclusion: I think there's a problem somewhere preventing them from spawning.

**Comment by NickMcConnell** [comment]
Fixed in 10b2a235e with whole new directory for them
